//
//  ISOLanguageCode.swift
//  LocalizationHelper
//
//  Created by Chung Tran on 14/01/2021.
//

import Foundation

struct ISOLanguageCode {
    var code: String
    var name: String
    var isSelected = false
}

extension ISOLanguageCode {
    static var all: [ISOLanguageCode] {
        [
            ISOLanguageCode(code: "af", name: "Afrikaans"),
            ISOLanguageCode(code: "af-ZA", name: "Afrikaans (South Africa)"),
            ISOLanguageCode(code: "ar", name: "Arabic"),
            ISOLanguageCode(code: "ar-AE", name: "Arabic (U.A.E.)"),
            ISOLanguageCode(code: "ar-BH", name: "Arabic (Bahrain)"),
            ISOLanguageCode(code: "ar-DZ", name: "Arabic (Algeria)"),
            ISOLanguageCode(code: "ar-EG", name: "Arabic (Egypt)"),
            ISOLanguageCode(code: "ar-IQ", name: "Arabic (Iraq)"),
            ISOLanguageCode(code: "ar-JO", name: "Arabic (Jordan)"),
            ISOLanguageCode(code: "ar-KW", name: "Arabic (Kuwait)"),
            ISOLanguageCode(code: "ar-LB", name: "Arabic (Lebanon)"),
            ISOLanguageCode(code: "ar-LY", name: "Arabic (Libya)"),
            ISOLanguageCode(code: "ar-MA", name: "Arabic (Morocco)"),
            ISOLanguageCode(code: "ar-OM", name: "Arabic (Oman)"),
            ISOLanguageCode(code: "ar-QA", name: "Arabic (Qatar)"),
            ISOLanguageCode(code: "ar-SA", name: "Arabic (Saudi Arabia)"),
            ISOLanguageCode(code: "ar-SY", name: "Arabic (Syria)"),
            ISOLanguageCode(code: "ar-TN", name: "Arabic (Tunisia)"),
            ISOLanguageCode(code: "ar-YE", name: "Arabic (Yemen)"),
            ISOLanguageCode(code: "az", name: "Azeri (Latin)"),
            ISOLanguageCode(code: "az-AZ", name: "Azeri (Latin) (Azerbaijan)"),
            ISOLanguageCode(code: "az-AZ", name: "Azeri (Cyrillic) (Azerbaijan)"),
            ISOLanguageCode(code: "be", name: "Belarusian"),
            ISOLanguageCode(code: "be-BY", name: "Belarusian (Belarus)"),
            ISOLanguageCode(code: "bg", name: "Bulgarian"),
            ISOLanguageCode(code: "bg-BG", name: "Bulgarian (Bulgaria)"),
            ISOLanguageCode(code: "bs-BA", name: "Bosnian (Bosnia and Herzegovina)"),
            ISOLanguageCode(code: "ca", name: "Catalan"),
            ISOLanguageCode(code: "ca-ES", name: "Catalan (Spain)"),
            ISOLanguageCode(code: "cs", name: "Czech"),
            ISOLanguageCode(code: "cs-CZ", name: "Czech (Czech Republic)"),
            ISOLanguageCode(code: "cy", name: "Welsh"),
            ISOLanguageCode(code: "cy-GB", name: "Welsh (United Kingdom)"),
            ISOLanguageCode(code: "da", name: "Danish"),
            ISOLanguageCode(code: "da-DK", name: "Danish (Denmark)"),
            ISOLanguageCode(code: "de", name: "German"),
            ISOLanguageCode(code: "de-AT", name: "German (Austria)"),
            ISOLanguageCode(code: "de-CH", name: "German (Switzerland)"),
            ISOLanguageCode(code: "de-DE", name: "German (Germany)"),
            ISOLanguageCode(code: "de-LI", name: "German (Liechtenstein)"),
            ISOLanguageCode(code: "de-LU", name: "German (Luxembourg)"),
            ISOLanguageCode(code: "dv", name: "Divehi"),
            ISOLanguageCode(code: "dv-MV", name: "Divehi (Maldives)"),
            ISOLanguageCode(code: "el", name: "Greek"),
            ISOLanguageCode(code: "el-GR", name: "Greek (Greece)"),
            ISOLanguageCode(code: "en", name: "English"),
            ISOLanguageCode(code: "en-AU", name: "English (Australia)"),
            ISOLanguageCode(code: "en-BZ", name: "English (Belize)"),
            ISOLanguageCode(code: "en-CA", name: "English (Canada)"),
            ISOLanguageCode(code: "en-CB", name: "English (Caribbean)"),
            ISOLanguageCode(code: "en-GB", name: "English (United Kingdom)"),
            ISOLanguageCode(code: "en-IE", name: "English (Ireland)"),
            ISOLanguageCode(code: "en-JM", name: "English (Jamaica)"),
            ISOLanguageCode(code: "en-NZ", name: "English (New Zealand)"),
            ISOLanguageCode(code: "en-PH", name: "English (Republic of the Philippines)"),
            ISOLanguageCode(code: "en-TT", name: "English (Trinidad and Tobago)"),
            ISOLanguageCode(code: "en-US", name: "English (United States)"),
            ISOLanguageCode(code: "en-ZA", name: "English (South Africa)"),
            ISOLanguageCode(code: "en-ZW", name: "English (Zimbabwe)"),
            ISOLanguageCode(code: "eo", name: "Esperanto"),
            ISOLanguageCode(code: "es", name: "Spanish"),
            ISOLanguageCode(code: "es-AR", name: "Spanish (Argentina)"),
            ISOLanguageCode(code: "es-BO", name: "Spanish (Bolivia)"),
            ISOLanguageCode(code: "es-CL", name: "Spanish (Chile)"),
            ISOLanguageCode(code: "es-CO", name: "Spanish (Colombia)"),
            ISOLanguageCode(code: "es-CR", name: "Spanish (Costa Rica)"),
            ISOLanguageCode(code: "es-DO", name: "Spanish (Dominican Republic)"),
            ISOLanguageCode(code: "es-EC", name: "Spanish (Ecuador)"),
            ISOLanguageCode(code: "es-ES", name: "Spanish (Castilian)"),
            ISOLanguageCode(code: "es-ES", name: "Spanish (Spain)"),
            ISOLanguageCode(code: "es-GT", name: "Spanish (Guatemala)"),
            ISOLanguageCode(code: "es-HN", name: "Spanish (Honduras)"),
            ISOLanguageCode(code: "es-MX", name: "Spanish (Mexico)"),
            ISOLanguageCode(code: "es-NI", name: "Spanish (Nicaragua)"),
            ISOLanguageCode(code: "es-PA", name: "Spanish (Panama)"),
            ISOLanguageCode(code: "es-PE", name: "Spanish (Peru)"),
            ISOLanguageCode(code: "es-PR", name: "Spanish (Puerto Rico)"),
            ISOLanguageCode(code: "es-PY", name: "Spanish (Paraguay)"),
            ISOLanguageCode(code: "es-SV", name: "Spanish (El Salvador)"),
            ISOLanguageCode(code: "es-UY", name: "Spanish (Uruguay)"),
            ISOLanguageCode(code: "es-VE", name: "Spanish (Venezuela)"),
            ISOLanguageCode(code: "et", name: "Estonian"),
            ISOLanguageCode(code: "et-EE", name: "Estonian (Estonia)"),
            ISOLanguageCode(code: "eu", name: "Basque"),
            ISOLanguageCode(code: "eu-ES", name: "Basque (Spain)"),
            ISOLanguageCode(code: "fa", name: "Farsi"),
            ISOLanguageCode(code: "fa-IR", name: "Farsi (Iran)"),
            ISOLanguageCode(code: "fi", name: "Finnish"),
            ISOLanguageCode(code: "fi-FI", name: "Finnish (Finland)"),
            ISOLanguageCode(code: "fo", name: "Faroese"),
            ISOLanguageCode(code: "fo-FO", name: "Faroese (Faroe Islands)"),
            ISOLanguageCode(code: "fr", name: "French"),
            ISOLanguageCode(code: "fr-BE", name: "French (Belgium)"),
            ISOLanguageCode(code: "fr-CA", name: "French (Canada)"),
            ISOLanguageCode(code: "fr-CH", name: "French (Switzerland)"),
            ISOLanguageCode(code: "fr-FR", name: "French (France)"),
            ISOLanguageCode(code: "fr-LU", name: "French (Luxembourg)"),
            ISOLanguageCode(code: "fr-MC", name: "French (Principality of Monaco)"),
            ISOLanguageCode(code: "gl", name: "Galician"),
            ISOLanguageCode(code: "gl-ES", name: "Galician (Spain)"),
            ISOLanguageCode(code: "gu", name: "Gujarati"),
            ISOLanguageCode(code: "gu-IN", name: "Gujarati (India)"),
            ISOLanguageCode(code: "he", name: "Hebrew"),
            ISOLanguageCode(code: "he-IL", name: "Hebrew (Israel)"),
            ISOLanguageCode(code: "hi", name: "Hindi"),
            ISOLanguageCode(code: "hi-IN", name: "Hindi (India)"),
            ISOLanguageCode(code: "hr", name: "Croatian"),
            ISOLanguageCode(code: "hr-BA", name: "Croatian (Bosnia and Herzegovina)"),
            ISOLanguageCode(code: "hr-HR", name: "Croatian (Croatia)"),
            ISOLanguageCode(code: "hu", name: "Hungarian"),
            ISOLanguageCode(code: "hu-HU", name: "Hungarian (Hungary)"),
            ISOLanguageCode(code: "hy", name: "Armenian"),
            ISOLanguageCode(code: "hy-AM", name: "Armenian (Armenia)"),
            ISOLanguageCode(code: "id", name: "Indonesian"),
            ISOLanguageCode(code: "id-ID", name: "Indonesian (Indonesia)"),
            ISOLanguageCode(code: "is", name: "Icelandic"),
            ISOLanguageCode(code: "is-IS", name: "Icelandic (Iceland)"),
            ISOLanguageCode(code: "it", name: "Italian"),
            ISOLanguageCode(code: "it-CH", name: "Italian (Switzerland)"),
            ISOLanguageCode(code: "it-IT", name: "Italian (Italy)"),
            ISOLanguageCode(code: "ja", name: "Japanese"),
            ISOLanguageCode(code: "ja-JP", name: "Japanese (Japan)"),
            ISOLanguageCode(code: "ka", name: "Georgian"),
            ISOLanguageCode(code: "ka-GE", name: "Georgian (Georgia)"),
            ISOLanguageCode(code: "kk", name: "Kazakh"),
            ISOLanguageCode(code: "kk-KZ", name: "Kazakh (Kazakhstan)"),
            ISOLanguageCode(code: "kn", name: "Kannada"),
            ISOLanguageCode(code: "kn-IN", name: "Kannada (India)"),
            ISOLanguageCode(code: "ko", name: "Korean"),
            ISOLanguageCode(code: "ko-KR", name: "Korean (Korea)"),
            ISOLanguageCode(code: "kok", name: "Konkani"),
            ISOLanguageCode(code: "kok-IN", name: "Konkani (India)"),
            ISOLanguageCode(code: "ky", name: "Kyrgyz"),
            ISOLanguageCode(code: "ky-KG", name: "Kyrgyz (Kyrgyzstan)"),
            ISOLanguageCode(code: "lt", name: "Lithuanian"),
            ISOLanguageCode(code: "lt-LT", name: "Lithuanian (Lithuania)"),
            ISOLanguageCode(code: "lv", name: "Latvian"),
            ISOLanguageCode(code: "lv-LV", name: "Latvian (Latvia)"),
            ISOLanguageCode(code: "mi", name: "Maori"),
            ISOLanguageCode(code: "mi-NZ", name: "Maori (New Zealand)"),
            ISOLanguageCode(code: "mk", name: "FYRO Macedonian"),
            ISOLanguageCode(code: "mk-MK", name: "FYRO Macedonian (Former Yugoslav Republic of Macedonia)"),
            ISOLanguageCode(code: "mn", name: "Mongolian"),
            ISOLanguageCode(code: "mn-MN", name: "Mongolian (Mongolia)"),
            ISOLanguageCode(code: "mr", name: "Marathi"),
            ISOLanguageCode(code: "mr-IN", name: "Marathi (India)"),
            ISOLanguageCode(code: "ms", name: "Malay"),
            ISOLanguageCode(code: "ms-BN", name: "Malay (Brunei Darussalam)"),
            ISOLanguageCode(code: "ms-MY", name: "Malay (Malaysia)"),
            ISOLanguageCode(code: "mt", name: "Maltese"),
            ISOLanguageCode(code: "mt-MT", name: "Maltese (Malta)"),
            ISOLanguageCode(code: "nb", name: "Norwegian (Bokm?l)"),
            ISOLanguageCode(code: "nb-NO", name: "Norwegian (Bokm?l) (Norway)"),
            ISOLanguageCode(code: "nl", name: "Dutch"),
            ISOLanguageCode(code: "nl-BE", name: "Dutch (Belgium)"),
            ISOLanguageCode(code: "nl-NL", name: "Dutch (Netherlands)"),
            ISOLanguageCode(code: "nn-NO", name: "Norwegian (Nynorsk) (Norway)"),
            ISOLanguageCode(code: "ns", name: "Northern Sotho"),
            ISOLanguageCode(code: "ns-ZA", name: "Northern Sotho (South Africa)"),
            ISOLanguageCode(code: "pa", name: "Punjabi"),
            ISOLanguageCode(code: "pa-IN", name: "Punjabi (India)"),
            ISOLanguageCode(code: "pl", name: "Polish"),
            ISOLanguageCode(code: "pl-PL", name: "Polish (Poland)"),
            ISOLanguageCode(code: "ps", name: "Pashto"),
            ISOLanguageCode(code: "ps-AR", name: "Pashto (Afghanistan)"),
            ISOLanguageCode(code: "pt", name: "Portuguese"),
            ISOLanguageCode(code: "pt-BR", name: "Portuguese (Brazil)"),
            ISOLanguageCode(code: "pt-PT", name: "Portuguese (Portugal)"),
            ISOLanguageCode(code: "qu", name: "Quechua"),
            ISOLanguageCode(code: "qu-BO", name: "Quechua (Bolivia)"),
            ISOLanguageCode(code: "qu-EC", name: "Quechua (Ecuador)"),
            ISOLanguageCode(code: "qu-PE", name: "Quechua (Peru)"),
            ISOLanguageCode(code: "ro", name: "Romanian"),
            ISOLanguageCode(code: "ro-RO", name: "Romanian (Romania)"),
            ISOLanguageCode(code: "ru", name: "Russian"),
            ISOLanguageCode(code: "ru-RU", name: "Russian (Russia)"),
            ISOLanguageCode(code: "sa", name: "Sanskrit"),
            ISOLanguageCode(code: "sa-IN", name: "Sanskrit (India)"),
            ISOLanguageCode(code: "se", name: "Sami (Northern)"),
            ISOLanguageCode(code: "se-FI", name: "Sami (Northern) (Finland)"),
            ISOLanguageCode(code: "se-FI", name: "Sami (Skolt) (Finland)"),
            ISOLanguageCode(code: "se-FI", name: "Sami (Inari) (Finland)"),
            ISOLanguageCode(code: "se-NO", name: "Sami (Northern) (Norway)"),
            ISOLanguageCode(code: "se-NO", name: "Sami (Lule) (Norway)"),
            ISOLanguageCode(code: "se-NO", name: "Sami (Southern) (Norway)"),
            ISOLanguageCode(code: "se-SE", name: "Sami (Northern) (Sweden)"),
            ISOLanguageCode(code: "se-SE", name: "Sami (Lule) (Sweden)"),
            ISOLanguageCode(code: "se-SE", name: "Sami (Southern) (Sweden)"),
            ISOLanguageCode(code: "sk", name: "Slovak"),
            ISOLanguageCode(code: "sk-SK", name: "Slovak (Slovakia)"),
            ISOLanguageCode(code: "sl", name: "Slovenian"),
            ISOLanguageCode(code: "sl-SI", name: "Slovenian (Slovenia)"),
            ISOLanguageCode(code: "sq", name: "Albanian"),
            ISOLanguageCode(code: "sq-AL", name: "Albanian (Albania)"),
            ISOLanguageCode(code: "sr-BA", name: "Serbian (Latin) (Bosnia and Herzegovina)"),
            ISOLanguageCode(code: "sr-BA", name: "Serbian (Cyrillic) (Bosnia and Herzegovina)"),
            ISOLanguageCode(code: "sr-SP", name: "Serbian (Latin) (Serbia and Montenegro)"),
            ISOLanguageCode(code: "sr-SP", name: "Serbian (Cyrillic) (Serbia and Montenegro)"),
            ISOLanguageCode(code: "sv", name: "Swedish"),
            ISOLanguageCode(code: "sv-FI", name: "Swedish (Finland)"),
            ISOLanguageCode(code: "sv-SE", name: "Swedish (Sweden)"),
            ISOLanguageCode(code: "sw", name: "Swahili"),
            ISOLanguageCode(code: "sw-KE", name: "Swahili (Kenya)"),
            ISOLanguageCode(code: "syr", name: "Syriac"),
            ISOLanguageCode(code: "syr-SY", name: "Syriac (Syria)"),
            ISOLanguageCode(code: "ta", name: "Tamil"),
            ISOLanguageCode(code: "ta-IN", name: "Tamil (India)"),
            ISOLanguageCode(code: "te", name: "Telugu"),
            ISOLanguageCode(code: "te-IN", name: "Telugu (India)"),
            ISOLanguageCode(code: "th", name: "Thai"),
            ISOLanguageCode(code: "th-TH", name: "Thai (Thailand)"),
            ISOLanguageCode(code: "tl", name: "Tagalog"),
            ISOLanguageCode(code: "tl-PH", name: "Tagalog (Philippines)"),
            ISOLanguageCode(code: "tn", name: "Tswana"),
            ISOLanguageCode(code: "tn-ZA", name: "Tswana (South Africa)"),
            ISOLanguageCode(code: "tr", name: "Turkish"),
            ISOLanguageCode(code: "tr-TR", name: "Turkish (Turkey)"),
            ISOLanguageCode(code: "tt", name: "Tatar"),
            ISOLanguageCode(code: "tt-RU", name: "Tatar (Russia)"),
            ISOLanguageCode(code: "ts", name: "Tsonga"),
            ISOLanguageCode(code: "uk", name: "Ukrainian"),
            ISOLanguageCode(code: "uk-UA", name: "Ukrainian (Ukraine)"),
            ISOLanguageCode(code: "ur", name: "Urdu"),
            ISOLanguageCode(code: "ur-PK", name: "Urdu (Islamic Republic of Pakistan)"),
            ISOLanguageCode(code: "uz", name: "Uzbek (Latin)"),
            ISOLanguageCode(code: "uz-UZ", name: "Uzbek (Latin) (Uzbekistan)"),
            ISOLanguageCode(code: "uz-UZ", name: "Uzbek (Cyrillic) (Uzbekistan)"),
            ISOLanguageCode(code: "vi", name: "Vietnamese"),
            ISOLanguageCode(code: "vi-VN", name: "Vietnamese (Viet Nam)"),
            ISOLanguageCode(code: "xh", name: "Xhosa"),
            ISOLanguageCode(code: "xh-ZA", name: "Xhosa (South Africa)"),
            ISOLanguageCode(code: "zh", name: "Chinese"),
            ISOLanguageCode(code: "zh-CN", name: "Chinese (S)"),
            ISOLanguageCode(code: "zh-HK", name: "Chinese (Hong Kong)"),
            ISOLanguageCode(code: "zh-MO", name: "Chinese (Macau)"),
            ISOLanguageCode(code: "zh-SG", name: "Chinese (Singapore)"),
            ISOLanguageCode(code: "zh-TW", name: "Chinese (T)"),
            ISOLanguageCode(code: "zu", name: "Zulu"),
            ISOLanguageCode(code: "zu-ZA", name: "Zulu (South Africa)")
        ]
    }
}
